# Generated by Django 5.1 on 2024-08-17 00:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='upload_resume',
            field=models.FileField(default=django.utils.timezone.now, upload_to='resume'),
            preserve_default=False,
        ),
    ]
